### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <*> 

### ISSUE THREAD

**Issue by jiangbingi** [apiggs/apiggs#10]
用自己项目生成的时候，报了下面这个错，但是没有这样的java文件
`Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 64: D:\workspace\trade-impl\src\main\java/******************************************************************.java
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:204)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$tryToSolveType$4(JavaParserTypeSolver.java:173)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4904)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 51 more`

**Comment by ayz6uem** [comment]
问题很奇怪，能否提供环境信息？

**Comment by jiangbingi** [comment]
需要什么环境信息呢，我又创建了一个新的的项目，弄了个接口，是可以生成成功的。

**Comment by ayz6uem** [comment]
应该是代码在解析时将****误认为一个类，所以想看看那个项目里有类似的代码吗？

**Comment by zpf1873215897** [comment]
我也遇到同样的问题，请问是如何解决的。
